// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZ-shc4kcu5hPaHnYL6uiWrdYpgud9V0',
    appId: '1:359971537312:web:dd9bbca7cbcf34374a24c5',
    messagingSenderId: '359971537312',
    projectId: 'prayerrecorder-486a1',
    authDomain: 'prayerrecorder-486a1.firebaseapp.com',
    storageBucket: 'prayerrecorder-486a1.appspot.com',
    measurementId: 'G-ZRVH976Q57',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyvzYtXX89d0anmi2d4iCKOz67EcidP0',
    appId: '1:359971537312:ios:80614bb6939df1704a24c5',
    messagingSenderId: '359971537312',
    projectId: 'prayerrecorder-486a1',
    storageBucket: 'prayerrecorder-486a1.appspot.com',
    iosBundleId: 'com.example.prayerrecorder',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyvzYtXX89d0anmi2d4iCKOz67EcidP0',
    appId: '1:359971537312:ios:80614bb6939df1704a24c5',
    messagingSenderId: '359971537312',
    projectId: 'prayerrecorder-486a1',
    storageBucket: 'prayerrecorder-486a1.appspot.com',
    iosBundleId: 'com.example.prayerrecorder',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWHbq6c2pKLBqdiPaUgJNGFN8ZM31O9I',
    appId: '1:359971537312:android:dd44859846da94d04a24c5',
    messagingSenderId: '359971537312',
    projectId: 'prayerrecorder-486a1',
    storageBucket: 'prayerrecorder-486a1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZ-shc4kcu5hPaHnYL6uiWrdYpgud9V0',
    appId: '1:359971537312:web:9b446efe7ed34ff64a24c5',
    messagingSenderId: '359971537312',
    projectId: 'prayerrecorder-486a1',
    authDomain: 'prayerrecorder-486a1.firebaseapp.com',
    storageBucket: 'prayerrecorder-486a1.appspot.com',
    measurementId: 'G-B9G2Z7V0GZ',
  );

}